import "./css/style.css";

import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Script from "next/script";
import Header from "@/components/ui/header";

// Load Google Inter font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// Load local Nacelle font with multiple weights/styles
const nacelle = localFont({
  src: [
    {
      path: "../public/fonts/nacelle-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/nacelle-italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/nacelle-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/nacelle-semibolditalic.woff2",
      weight: "600",
      style: "italic",
    },
  ],
  variable: "--font-nacelle",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${nacelle.variable}`}>
      <head>
        {/* Preload image */}
        <link rel="preload" href="/banner.webp" as="image" />

        {/* Google Tag Manager loader */}
        <Script
          id="gtm-init"
          strategy="lazyOnload"
          dangerouslySetInnerHTML={{
            __html: `
              document.addEventListener('DOMContentLoaded', () => {
                setTimeout(initGTM, 3500);
              });
              document.addEventListener('scroll', initGTMOnEvent);
              document.addEventListener('mousemove', initGTMOnEvent);
              document.addEventListener('touchstart', initGTMOnEvent);
              
              function initGTMOnEvent(event) {
                initGTM();
                event.currentTarget.removeEventListener(event.type, initGTMOnEvent);
              }

              window.dataLayer = window.dataLayer || [];
              window.dataLayer.push({
                originalLocation: document.location.protocol + '//' +
                                  document.location.hostname +
                                  document.location.pathname +
                                  document.location.search
              });

              function initGTM() {
                if (window.gtmDidInit) return;
                window.gtmDidInit = true;
                
                const script = document.createElement('script');
                script.type = 'text/javascript';
                script.async = true;
                script.onload = () => {
                  dataLayer.push({
                    event: 'gtm.js',
                    'gtm.start': new Date().getTime(),
                    'gtm.uniqueEventId': 0
                  });
                };
                script.src = 'https://www.googletagmanager.com/gtm.js?id=GTM-K8PBTTFP';
                document.head.appendChild(script);
              }
            `,
          }}
        />
      </head>
      <body className="bg-white font-inter text-base text-gray-200 antialiased">
        {/* GTM fallback for users with JS disabled */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-K8PBTTFP"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>

        {/* Main content layout */}
        <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
